### ISSUE TITLE
Facts gathering with Bash/FreeBSD and script typo

### ISSUE THREAD

**Issue by olivermussell** [puppetlabs/puppetlabs-facts#24]
I’m running puppet bolt from a Mac to connect to FreeBSD servers. I’m trying to gather facts as part of the plan run and running into errors. My setup:

Bolt 1.13.1

bolt.yaml

```
inventoryfile: "./inventory.yaml"
format: human
ssh:
  host-key-check: false
  user: my-user-name
  interpreters:
    .rb: /usr/local/bin/ruby
```

inventory.yaml

```
groups:
  - name: server1
    nodes:
      - server1.domain.com
    features: ['puppet-agent']
```

site/profiles/plans/test.pp

```
plan profiles::test(
  TargetSpec $nodes,
) {

  run_plan(facts, nodes => $nodes)

  apply_prep($nodes)

  apply($nodes) {

    file { '/home/my-user-name/test':
      ensure => directory,
    }

  }

}
```

When I run `bolt plan run profiles::test --nodes server1 --debug` or likewise run the facts plan `bolt plan run facts --nodes server1 --debug` or task `bolt task run facts --nodes server1 --debug`:

```
Running task facts with '{"_task"=>"facts"}' on [“server1”]
Running task run '#<struct Bolt::Task name="facts", file=nil, files=[{"name"=>"ruby.rb", "path"=>"/Users/oliver/puppet-control/modules/facts/tasks/ruby.rb"}, {"name"=>"powershell.ps1", "path"=>"/Users/oliver/puppet-control/modules/facts/tasks/powershell.ps1"}, {"name"=>"bash.sh", "path"=>"/Users/oliver/puppet-control/modules/facts/tasks/bash.sh"}], metadata={"description"=>"Gather system facts", "parameters"=>{}, "input_method"=>"environment", "implementations"=>[{"name"=>"ruby.rb", "requirements"=>["puppet-agent"]}, {"name"=>"powershell.ps1", "requirements"=>["powershell"]}, {"name"=>"bash.sh", "requirements"=>["shell"]}]}>' on server1
Opened session
Executing: mkdir -m 700 /tmp/eff5a9e2-2244-4ab8-9b4c-127c72e1ada4
Command returned successfully
Executing: chmod u\+x /tmp/eff5a9e2-2244-4ab8-9b4c-127c72e1ada4/ruby.rb
Command returned successfully
Executing: PT__task=facts /usr/local/bin/ruby /tmp/eff5a9e2-2244-4ab8-9b4c-127c72e1ada4/ruby.rb
stderr: PT__task=facts: Command not found.
Command failed with exit code 1
Executing: rm -rf /tmp/eff5a9e2-2244-4ab8-9b4c-127c72e1ada4
Command returned successfully
Closed session
{"node”:”server1”,”status":"failure","result":{"_output":"","_error":{"kind":"puppetlabs.tasks/task-error","issue_code":"TASK_ERROR","msg":"The task failed with exit code 1:\nPT__task=facts: Command not found.\n","details":{"exit_code":1}}}}
Finished: task facts with 1 failure in 1.4 sec
Finished: plan facts in 1.42 sec
{
  "kind": "bolt/run-failure",
  "msg": "Plan aborted: run_task 'facts' failed on 1 nodes",
  "details": {
    "action": "run_task",
    "object": "facts",
    "result_set": [
      {
        "node": “server1”,
        "status": "failure",
        "result": {
          "_output": "",
          "_error": {
            "kind": "puppetlabs.tasks/task-error",
            "issue_code": "TASK_ERROR",
            "msg": "The task failed with exit code 1:\nPT__task=facts: Command not found.\n",
            "details": {
              "exit_code": 1
            }
          }
        }
      }
    ]
  }
}
```

This appears to be failing due to my user account on the server using CSH as the login shell, specifically, the way that you set a environment variable in CSH is different to Bash so this: `PT__task=facts: Command not found` won’t work. If I change my shell to Bash instead, I no longer get this error.

I’m not expecting the plan/task to work with every shell, but it may be worth adding to the documentation that you need to make sure that if you are using the SSH transport, its going to run the Bash shell script, which requires your SSH user account to be using Bash as the login shell. I can get around this for now by either changing my shell or setting up a user just for bolt using the Bash shell.

One other thing is that if I run the `facts::bash` task directly, it works apart from one line of error:

```
Executing: PT__task=facts::bash /tmp/a6568bd4-12e6-422b-99cd-1cf676ca6938/bash.sh
stderr: /tmp/a6568bd4-12e6-422b-99cd-1cf676ca6938/bash.sh: line 42: [-e: command not found
```

It appears that the `facts/tasks/bash.sh` file has a typo. The line:

```
elif [-e /usr/lib/os-release ]; then
```

should be:

```
elif [ -e /usr/lib/os-release ]; then
```

(note the space between `[` and `-e` )

After manually changing this in the module and running again, it no longer errors.

**Comment by donoghuc** [comment]
@olivermussell Thanks for filing this issue. I created https://tickets.puppetlabs.com/browse/MODULES-8750 to track this bug fix as well as some other possible improvements to the bash implementation of the task. I will also do some research and file a ticket around your suggestion of documenting the remote shell configuration.

**Comment by MikaelSmith** [comment]
I think the other - environment variable handling - would need to be addressed in Bolt.

**Comment by donoghuc** [comment]
@olivermussell The bug you pointed out in the bash task implementation has been included in a `0.5.1` release of the `facts` module. It will be packaged with bolt in the next release. Thanks for reporting the issue.

**Comment by lucywyman** [comment]
Can this issue be closed?

**Comment by olivermussell** [comment]
Yes, thanks
