### ISSUE TITLE
Warning: Module 'puppetlabs-facts' (v1.0.0) fails to meet some dependencies...

### ISSUE THREAD

**Issue by ola-pt** [puppetlabs/puppetlabs-facts#40]
## Bug Description:
After running `puppet module list` on my puppetmaster server the following error code appears:
`#E8F214`
```bash
Warning: Module 'puppetlabs-facts' (v1.0.0) fails to meet some dependencies:
  'puppetlabs-puppet_agent' (v3.1.0) requires 'puppetlabs-facts' (>= 0.5.0 < 1.0.0)
```

In my puppet runs the following error message appears as well for any external facts I have in use for a node group:
```
error while processing "%1%" for external facts: %2%
Source:	Facter
```

## Possible Fix?:
Changing the dependency for 'puppetlabs-puppet_agent' (v3.1.0) be changed to 'puppetlabs-facts' (>= 0.5.0 <= 1.0.0).

## Steps to Reproduce
1. Use a Puppetfile with the following modules listed (so that the ):
```
mod 'puppetlabs-exec', :latest
mod 'puppetlabs-apt', :latest
mod 'puppetlabs-facter_task', :latest
mod 'puppetlabs-facts', :latest
mod 'puppetlabs-inifile', :latest
mod 'puppetlabs-package', :latest
mod 'puppetlabs-pwshlib', :latest
mod 'puppetlabs-powershell', :latest
mod 'puppetlabs-puppet_agent', :latest
mod 'puppetlabs-puppet_conf', :latest
mod 'puppetlabs-service', :latest
mod 'puppetlabs-stdlib', :latest
mod 'puppetlabs-translate', :latest
mod 'puppetlabs-bolt_shim', :latest
mod 'puppetlabs-apply_helpers', :latest
```
2. Run the following command:
``puppet module list``

**Comment by npwalker** [comment]
This was resolved in the puppet_agent module

https://github.com/puppetlabs/puppetlabs-puppet_agent/commit/0f777f8372f6c0f2fae24e3673d25ca39b0cafd6
