### ISSUE TITLE
plan metadata

### ISSUE THREAD

**Issue by f3rr** [puppetlabs/puppetlabs-facts#42]
## Describe the Bug
metadata for plans missing?

## Expected Behavior
finding working example with metadata

## Steps to Reproduce
1. Go to '...' puppetlabs puppet enterprise latest documentation
https://puppet.com/docs/pe/2019.8/writing_plans_in_puppet_language_pe.html#example_plans_pe

2. Click on 'facts plan'

**Comment by donoghuc** [comment]
https://github.com/puppetlabs/puppetlabs-facts/pull/43

**Comment by f3rr** [comment]
Let me understand this
So you write json files for modules metadata.
you write json files for tasks metadata.
you write file header inside a plan for plan metadata.
I hope i understood it wrong and this is not the case, or its just a joke, right?

**Comment by donoghuc** [comment]
All plan metadata is parsed from the plan file itself. There is no separate metadata file for plans.

**Comment by f3rr** [comment]
So i tried the following:
# @summary
# test plan
#
# @param environment environment to use
#
# @return foo
plan <name>(
  String $environment
)
{
 return 'OK'
}

still getting "Error loading metadata: Not Found"

**Comment by f3rr** [comment]
after some testing, it looks like the problem is if i put the plan into a subdir.
its working directly in plans directory, but not in any subdirs.

**Comment by lucywyman** [comment]
Does your plan have the correct name if it's in a subdir? Nested plans need to be titled `<module>::<subdir>::<plan_name>`. For example, if I have a plan at `mymodule/plans/foo/init.pp` the plan is named `mymodule::foo::init` and needs to start with:
```
# @summary
#   Test plan
plan mymodule::foo::init (
....
```

You also, as demoed above, need to indent the summary by at least one space (standard is 2 spaces) for it to be read by Puppet strings.

**Comment by lucywyman** [comment]
Ohhhhh I see this is in PE, not Bolt :facepalm: It sounds like subdirs are supported in PE 2019.8.1, which may be the issue depending on your version?

**Comment by f3rr** [comment]
Sorry for my late answer, bug seems to be fixed now, so issue can be closed

**Comment by f3rr** [comment]
thank you everyone who spent time on this.
